version: '3.10'

services:
  postgres:
    image: postgres:latest
    container_name: db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgres_data: